name: learn-github-actions
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
       name: node-app
    
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
